# Generated by Django 5.1.4 on 2025-01-23 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_application', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datas',
            old_name='Conform_Password',
            new_name='Confirm_Password',
        ),
    ]
