# Generated by Django 5.1.4 on 2025-01-23 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_application', '0002_rename_conform_password_datas_confirm_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emailid', models.EmailField(max_length=50)),
                ('EmailPassword', models.CharField(max_length=20)),
            ],
        ),
    ]
